# Generated by Django 3.2.7 on 2021-09-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_message_id', models.BigIntegerField(blank=True, null=True)),
                ('info_message_id', models.BigIntegerField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'question_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('issuer_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('channel_id', models.BigIntegerField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchemaMigrations',
            fields=[
                ('version', models.BigIntegerField(primary_key=True, serialize=False)),
                ('inserted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schema_migrations',
                'managed': False,
            },
        ),
    ]
